name: "Terratest GitHub Action"
on:
  pull_request:
    branches: [development, main]
  push:
    branches: [development, main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  terratest:
    name: terratest
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
      - name: Set up Go (1.24)
        uses: actions/setup-go@v2
        with:
          go-version: 1.24
        id: go
      - uses: azure/setup-kubectl@v4
        id: install
      - name: Run 'go test -v -timeout 60m'
        run: |
          cd test
          go mod download
          go test -v -timeout 60m
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
      - name: release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.2
            @semantic-release/changelog@6.0.1
